[package]
name = "movie_review"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "movie_review"
crate-type = ["cdylib", "rlib"]

[dependencies]
solana-program = "1.18"
borsh = "1"
